version: '3.8'

services:
  app:
    image: lab8-cicd-app:latest
    build: .
    ports:
      - "3000:3000"
  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: